import type { Chat, Message, User } from '@/types';

export const demoUser: User = {
  id: 'user-1',
  username: 'johndoe',
  email: 'john@example.com',
  phone: '+1234567890',
  firstName: 'John',
  lastName: 'Doe',
  avatar: '',
  bio: 'Hey there! I am using SUP Messenger',
  isOnline: true,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const demoChats: Chat[] = [
  {
    id: 'chat-1',
    type: 'private',
    name: 'Alice Smith',
    avatar: '',
    participants: ['user-1', 'user-2'],
    unreadCount: 3,
    isPinned: true,
    isArchived: false,
    isMuted: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(),
    lastMessage: {
      id: 'msg-1',
      chatId: 'chat-1',
      senderId: 'user-2',
      content: 'Hey! How are you doing?',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 5),
      updatedAt: new Date(Date.now() - 1000 * 60 * 5),
    },
  },
  {
    id: 'chat-2',
    type: 'group',
    name: 'Dev Team',
    avatar: '',
    participants: ['user-1', 'user-2', 'user-3', 'user-4'],
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isMuted: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    lastMessage: {
      id: 'msg-2',
      chatId: 'chat-2',
      senderId: 'user-3',
      content: 'Meeting at 3 PM',
      type: 'text',
      status: 'delivered',
      createdAt: new Date(Date.now() - 1000 * 60 * 30),
      updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    },
  },
  {
    id: 'chat-3',
    type: 'private',
    name: 'Bob Johnson',
    avatar: '',
    participants: ['user-1', 'user-5'],
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isMuted: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60),
    lastMessage: {
      id: 'msg-3',
      chatId: 'chat-3',
      senderId: 'user-1',
      content: 'Thanks!',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60),
    },
  },
];

export const demoMessages: Record<string, Message[]> = {
  'chat-1': [
    {
      id: 'msg-11',
      chatId: 'chat-1',
      senderId: 'user-1',
      content: 'Hi Alice! How are you?',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 10),
      updatedAt: new Date(Date.now() - 1000 * 60 * 10),
    },
    {
      id: 'msg-12',
      chatId: 'chat-1',
      senderId: 'user-2',
      content: 'Hey! I\'m good, thanks! How about you?',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 8),
      updatedAt: new Date(Date.now() - 1000 * 60 * 8),
    },
    {
      id: 'msg-13',
      chatId: 'chat-1',
      senderId: 'user-1',
      content: 'Great! Want to grab coffee later?',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 6),
      updatedAt: new Date(Date.now() - 1000 * 60 * 6),
    },
    {
      id: 'msg-14',
      chatId: 'chat-1',
      senderId: 'user-2',
      content: 'Sure! What time works for you?',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 5),
      updatedAt: new Date(Date.now() - 1000 * 60 * 5),
    },
  ],
  'chat-2': [
    {
      id: 'msg-21',
      chatId: 'chat-2',
      senderId: 'user-3',
      content: 'Team meeting at 3 PM today',
      type: 'text',
      status: 'delivered',
      createdAt: new Date(Date.now() - 1000 * 60 * 30),
      updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    },
    {
      id: 'msg-22',
      chatId: 'chat-2',
      senderId: 'user-4',
      content: 'Got it! I\'ll be there',
      type: 'text',
      status: 'delivered',
      createdAt: new Date(Date.now() - 1000 * 60 * 28),
      updatedAt: new Date(Date.now() - 1000 * 60 * 28),
    },
  ],
};

// Helper function to load demo data into stores
export const loadDemoData = () => {
  // This can be used for development/testing
  return {
    user: demoUser,
    chats: demoChats,
    messages: demoMessages,
  };
};
